"""Fail-closed Cargo Chief policy for Slack-driven Claude processes.

This module deliberately has no Slack or bot imports.  Startup policy and
command construction can therefore be tested without credentials or a live
Claude process.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import subprocess
from typing import Mapping


GENERATED_MARKER = (
    "<!-- generated by cargo-chief-agent-kit/setup.sh — edits below the marker "
    "survive regeneration -->"
)
ALLOWED_PERMISSION_MODES = {"auto"}
ALLOWED_BACKENDS = {"claude"}
ALLOWED_EFFORTS = {"low", "medium", "high", "xhigh", "max"}


class SafetyError(RuntimeError):
    """A configuration or local-state condition that must refuse a spawn."""


def parse_ids(value: str) -> frozenset[str]:
    return frozenset(part.strip() for part in value.split(",") if part.strip())


@dataclass(frozen=True)
class AuthorityPolicy:
    authorized_users: frozenset[str]
    approvers: frozenset[str]

    @classmethod
    def from_env(cls, env: Mapping[str, str] = os.environ) -> "AuthorityPolicy":
        policy = cls(
            authorized_users=parse_ids(env.get("AUTHORIZED_USERS", "")),
            approvers=parse_ids(env.get("CARGO_CHIEF_APPROVERS", "")),
        )
        errors = []
        if not policy.authorized_users:
            errors.append("AUTHORIZED_USERS must name at least one Slack user")
        if not policy.approvers:
            errors.append("CARGO_CHIEF_APPROVERS must name at least one Slack user")
        unknown = policy.approvers - policy.authorized_users
        if unknown:
            errors.append("every CARGO_CHIEF_APPROVERS entry must also be authorized")
        if errors:
            raise SafetyError("; ".join(errors))
        return policy

    def allows(self, user_id: str) -> bool:
        return bool(user_id) and user_id in self.authorized_users

    def can_approve(self, user_id: str) -> bool:
        return self.allows(user_id) and user_id in self.approvers


@dataclass(frozen=True)
class RoomPolicy:
    root: Path
    permission_mode: str
    overlay: Path
    escalation_channel: str
    backend: str
    model: str
    effort: str
    role: str


def load_model_config(path: Path) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SafetyError(f"missing room configuration: {path}") from exc
    except (OSError, json.JSONDecodeError) as exc:
        raise SafetyError(f"unreadable room configuration {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise SafetyError("model-config.json must contain an object")
    return value


def resolve_room_policy(config: dict, channel_id: str, user_id: str) -> RoomPolicy:
    entry = dict(config.get("channels", {}).get(channel_id, {}))
    if channel_id.startswith("D"):
        entry.update(config.get("dm_users", {}).get(user_id, {}))

    required = (
        "root", "permission_mode", "autonomous_overlay", "private_escalation_channel",
        "backend", "model", "effort",
    )
    missing = [key for key in required if not entry.get(key)]
    if missing:
        raise SafetyError(
            f"room {channel_id!r} is not Cargo Chief configured; missing: {', '.join(missing)}"
        )

    root = Path(entry["root"]).expanduser().resolve()
    overlay_value = Path(entry["autonomous_overlay"]).expanduser()
    overlay = overlay_value if overlay_value.is_absolute() else root / overlay_value
    permission_mode = str(entry["permission_mode"])
    backend = str(entry["backend"]).lower()
    effort = str(entry["effort"])
    model = str(entry["model"])
    role = str(entry.get("role", "eng"))

    if permission_mode not in ALLOWED_PERMISSION_MODES:
        raise SafetyError(f"room {channel_id!r} permission_mode must be 'auto'")
    if backend not in ALLOWED_BACKENDS:
        raise SafetyError(f"room {channel_id!r} backend {backend!r} is not allowed")
    if effort not in ALLOWED_EFFORTS:
        raise SafetyError(f"room {channel_id!r} has unsupported effort {effort!r}")
    allowed_models = config.get("models")
    if not isinstance(allowed_models, list) or not allowed_models:
        raise SafetyError("model-config.json must define a non-empty models allowlist")
    if model not in allowed_models or not model.startswith("claude-"):
        raise SafetyError(f"room {channel_id!r} model {model!r} is not allowlisted")
    if role not in {"eng", "support"}:
        raise SafetyError(f"room {channel_id!r} has unsupported role {role!r}")

    return RoomPolicy(
        root=root,
        permission_mode=permission_mode,
        overlay=overlay.absolute(),
        escalation_channel=str(entry["private_escalation_channel"]),
        backend=backend,
        model=model,
        effort=effort,
        role=role,
    )


def _git(repo: Path, *args: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), *args],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise SafetyError(f"cannot inspect git checkout {repo}") from exc
    return result.stdout.strip()


def _check_shared_clone(repo: Path, name: str) -> list[str]:
    if not repo.is_dir():
        raise SafetyError(f"{name} clone is missing: {repo}")
    branch = _git(repo, "branch", "--show-current")
    if branch != "master":
        raise SafetyError(f"{name} clone is on {branch or 'detached HEAD'}, expected master")
    if _git(repo, "status", "--porcelain"):
        raise SafetyError(f"{name} clone is not clean")

    warnings = []
    try:
        behind = int(_git(repo, "rev-list", "--count", "HEAD..origin/master") or "0")
    except (SafetyError, ValueError):
        warnings.append(f"{name} local origin/master staleness could not be checked")
    else:
        if behind:
            warnings.append(f"{name} is {behind} commit(s) behind local origin/master")
    return warnings


def _check_generated_agents(root: Path, kit: Path, role: str) -> None:
    agents = root / "AGENTS.md"
    try:
        installed = agents.read_text(encoding="utf-8")
        base = (kit / "AGENTS.base.md").read_text(encoding="utf-8").rstrip("\n")
        role_text = (kit / "roles" / role / "ROLE.md").read_text(encoding="utf-8").rstrip("\n")
    except OSError as exc:
        raise SafetyError(f"cannot read generated instruction inputs: {exc}") from exc
    if GENERATED_MARKER not in installed:
        raise SafetyError("AGENTS.md is not a generated Cargo Chief instruction file")
    generated = installed.split(GENERATED_MARKER, 1)[0].rstrip("\n")
    expected = f"{base}\n\n{role_text}"
    if generated != expected:
        raise SafetyError(f"AGENTS.md is stale for the configured {role} role")

    claude = root / "CLAUDE.md"
    if not claude.is_symlink() or claude.resolve() != agents.resolve():
        raise SafetyError("CLAUDE.md must be a symlink to AGENTS.md")


def preflight_room(policy: RoomPolicy) -> list[str]:
    root = policy.root
    if not root.is_dir():
        raise SafetyError(f"Cargo Chief root is missing: {root}")
    kit = root / "agent-kit"
    docs = root / "docs"
    warnings = _check_shared_clone(kit, "agent-kit")
    warnings.extend(_check_shared_clone(docs, "docs"))

    overlay = policy.overlay
    try:
        overlay_relative = overlay.relative_to(kit)
    except ValueError as exc:
        raise SafetyError("autonomous overlay must live inside agent-kit") from exc
    if not overlay.is_file() or overlay.is_symlink() or not overlay.read_text(encoding="utf-8").strip():
        raise SafetyError(f"autonomous overlay must be a non-empty regular file: {overlay}")
    try:
        tracked = _git(kit, "ls-files", "--error-unmatch", str(overlay_relative))
    except SafetyError as exc:
        raise SafetyError("autonomous overlay is not tracked by agent-kit") from exc
    if not tracked:
        raise SafetyError("autonomous overlay is not tracked by agent-kit")

    _check_generated_agents(root, kit, policy.role)
    return warnings


def build_claude_command(
    policy: RoomPolicy,
    *,
    initial_prompt: str,
    model_prompt: str = "",
    session_id: str | None = None,
) -> list[str]:
    overlay = policy.overlay.read_text(encoding="utf-8").strip()
    appended = "\n\n".join(part for part in (overlay, model_prompt.strip()) if part)
    command = [
        "claude", "-p", initial_prompt,
        "--input-format", "stream-json",
        "--output-format", "stream-json",
        "--verbose",
        "--effort", policy.effort,
        "--model", policy.model,
        "--permission-mode", policy.permission_mode,
        "--append-system-prompt", appended,
    ]
    if session_id:
        command.extend(["--resume", session_id])
    return command
