"""Fail-closed Cargo Chief policy for Slack-driven Claude processes.

This module deliberately has no Slack or bot imports.  Startup policy and
command construction can therefore be tested without credentials or a live
Claude process.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import subprocess
import time
from typing import Mapping


GENERATED_MARKER = (
    "<!-- generated by cargo-chief-agent-kit/setup.sh — edits below the marker "
    "survive regeneration -->"
)
ALLOWED_PERMISSION_MODES = {"auto"}
ALLOWED_BACKENDS = {"claude"}
ALLOWED_EFFORTS = {"low", "medium", "high", "xhigh", "max"}


class SafetyError(RuntimeError):
    """A configuration or local-state condition that must refuse a spawn."""


def find_workspace_root(source_dir: Path) -> Path:
    source_dir = source_dir.resolve()
    for candidate in (source_dir, *source_dir.parents):
        if (candidate / "agent-kit").is_dir() and (candidate / "docs").is_dir():
            return candidate
    raise SafetyError("cannot locate Cargo Chief workspace root from harness checkout")


def validate_secret_env_path(path: Path, *, workspace_root: Path) -> Path:
    path = path.expanduser()
    if not path.is_absolute():
        raise SafetyError("CARGO_CHIEF_ENV_FILE must be absolute")
    normalized = path.resolve(strict=False)
    workspace_root = workspace_root.resolve()
    if normalized == workspace_root or workspace_root in normalized.parents:
        raise SafetyError("CARGO_CHIEF_ENV_FILE must be outside the Cargo Chief workspace")
    if not path.is_file() or path.is_symlink():
        raise SafetyError(f"external credential file is missing or unsafe: {path}")
    if path.stat().st_mode & 0o777 != 0o600:
        raise SafetyError("CARGO_CHIEF_ENV_FILE must have mode 600")
    return path


def parse_ids(value: str) -> frozenset[str]:
    return frozenset(part.strip() for part in value.split(",") if part.strip())


@dataclass(frozen=True)
class AuthorityPolicy:
    authorized_users: frozenset[str]
    approvers: frozenset[str]

    @classmethod
    def from_env(cls, env: Mapping[str, str] = os.environ) -> "AuthorityPolicy":
        policy = cls(
            authorized_users=parse_ids(env.get("AUTHORIZED_USERS", "")),
            approvers=parse_ids(env.get("CARGO_CHIEF_APPROVERS", "")),
        )
        errors = []
        if not policy.authorized_users:
            errors.append("AUTHORIZED_USERS must name at least one Slack user")
        if not policy.approvers:
            errors.append("CARGO_CHIEF_APPROVERS must name at least one Slack user")
        unknown = policy.approvers - policy.authorized_users
        if unknown:
            errors.append("every CARGO_CHIEF_APPROVERS entry must also be authorized")
        if errors:
            raise SafetyError("; ".join(errors))
        return policy

    def allows(self, user_id: str) -> bool:
        return bool(user_id) and user_id in self.authorized_users

    def can_approve(self, user_id: str) -> bool:
        return self.allows(user_id) and user_id in self.approvers


@dataclass(frozen=True)
class RoomPolicy:
    root: Path
    permission_mode: str
    overlay: Path
    escalation_channel: str
    backend: str
    model: str
    effort: str
    role: str


def _env_bool(env: Mapping[str, str], key: str, default: bool = False) -> bool:
    value = env.get(key)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise SafetyError(f"{key} must be true or false")


@dataclass(frozen=True)
class RuntimePolicy:
    root: Path
    log_dir: Path
    state_dir: Path
    temp_dir: Path
    claude_timeout: int
    max_live_sessions: int
    file_transfer_enabled: bool
    transcript_search_enabled: bool

    @classmethod
    def from_env(
        cls,
        env: Mapping[str, str] = os.environ,
        *,
        source_dir: Path,
        workspace_root: Path,
        home: Path | None = None,
    ) -> "RuntimePolicy":
        home = (home or Path.home()).resolve()
        configured = env.get("CARGO_CHIEF_RUNTIME_DIR", "").strip()
        root = Path(configured).expanduser() if configured else home / ".local/state/cargo-chief/home-base"
        if not root.is_absolute():
            raise SafetyError("CARGO_CHIEF_RUNTIME_DIR must be absolute")
        root = root.absolute()
        source_dir = source_dir.resolve()
        workspace_root = workspace_root.resolve()
        if source_dir != workspace_root and workspace_root not in source_dir.parents:
            raise SafetyError("harness checkout must be inside the Cargo Chief workspace")
        normalized_root = root.resolve(strict=False)
        if normalized_root == workspace_root or workspace_root in normalized_root.parents:
            raise SafetyError("CARGO_CHIEF_RUNTIME_DIR must be outside the Cargo Chief workspace")

        try:
            timeout = int(env.get("CLAUDE_TIMEOUT", "600"))
            max_sessions = int(env.get("MAX_LIVE_SESSIONS", "1"))
        except ValueError as exc:
            raise SafetyError("CLAUDE_TIMEOUT and MAX_LIVE_SESSIONS must be integers") from exc
        if not 1 <= timeout <= 900:
            raise SafetyError("CLAUDE_TIMEOUT must be between 1 and 900 seconds for Gate A")
        if max_sessions != 1:
            raise SafetyError("MAX_LIVE_SESSIONS must be 1 for Gate A")

        file_transfer = _env_bool(env, "ENABLE_FILE_TRANSFER", False)
        transcript_search = _env_bool(env, "ENABLE_TRANSCRIPT_SEARCH", False)
        if file_transfer:
            raise SafetyError("ENABLE_FILE_TRANSFER must remain false for Gate A")
        if transcript_search:
            raise SafetyError("ENABLE_TRANSCRIPT_SEARCH must remain false for Gate A")

        return cls(
            root=root,
            log_dir=root / "logs",
            state_dir=root / "state",
            temp_dir=root / "tmp",
            claude_timeout=timeout,
            max_live_sessions=max_sessions,
            file_transfer_enabled=file_transfer,
            transcript_search_enabled=transcript_search,
        )

    def prepare(self) -> None:
        if self.root.exists() and (not self.root.is_dir() or self.root.is_symlink()):
            raise SafetyError("CARGO_CHIEF_RUNTIME_DIR must be a regular directory")
        for directory in (self.root, self.log_dir, self.state_dir, self.temp_dir):
            directory.mkdir(mode=0o700, parents=True, exist_ok=True)
            directory.chmod(0o700)

    def cleanup_temp(self, *, older_than_seconds: int = 24 * 60 * 60, now: float | None = None) -> int:
        now = now if now is not None else time.time()
        removed = 0
        for path in self.temp_dir.iterdir():
            if path.is_file() and not path.is_symlink() and now - path.stat().st_mtime > older_than_seconds:
                path.unlink()
                removed += 1
        return removed


def write_private_json(path: Path, value: object, *, indent: int | None = None) -> None:
    path.write_text(json.dumps(value, indent=indent), encoding="utf-8")
    path.chmod(0o600)


def format_audit_metadata(
    kind: str,
    *,
    user: str,
    channel: str,
    thread: str,
    message_length: int,
    response_length: int | None = None,
    session_id: str | None = None,
    duration: float | None = None,
) -> str:
    fields = [
        kind,
        f"USER:{user}",
        f"CHANNEL:{channel}",
        f"THREAD:{thread}",
        f"MSG_LEN:{message_length}",
    ]
    if response_length is not None:
        fields.append(f"RESP_LEN:{response_length}")
    if session_id is not None:
        fields.append(f"SESSION:{session_id}")
    if duration is not None:
        fields.append(f"DURATION:{duration:.1f}s")
    return " | ".join(fields)


def load_model_config(path: Path) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SafetyError(f"missing room configuration: {path}") from exc
    except (OSError, json.JSONDecodeError) as exc:
        raise SafetyError(f"unreadable room configuration {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise SafetyError("model-config.json must contain an object")
    return value


def resolve_room_policy(config: dict, channel_id: str, user_id: str) -> RoomPolicy:
    entry = dict(config.get("channels", {}).get(channel_id, {}))
    if channel_id.startswith("D"):
        entry.update(config.get("dm_users", {}).get(user_id, {}))

    required = (
        "root", "permission_mode", "autonomous_overlay", "private_escalation_channel",
        "backend", "model", "effort",
    )
    missing = [key for key in required if not entry.get(key)]
    if missing:
        raise SafetyError(
            f"room {channel_id!r} is not Cargo Chief configured; missing: {', '.join(missing)}"
        )

    root = Path(entry["root"]).expanduser().resolve()
    overlay_value = Path(entry["autonomous_overlay"]).expanduser()
    overlay = overlay_value if overlay_value.is_absolute() else root / overlay_value
    permission_mode = str(entry["permission_mode"])
    backend = str(entry["backend"]).lower()
    effort = str(entry["effort"])
    model = str(entry["model"])
    role = str(entry.get("role", "eng"))

    if permission_mode not in ALLOWED_PERMISSION_MODES:
        raise SafetyError(f"room {channel_id!r} permission_mode must be 'auto'")
    if backend not in ALLOWED_BACKENDS:
        raise SafetyError(f"room {channel_id!r} backend {backend!r} is not allowed")
    if effort not in ALLOWED_EFFORTS:
        raise SafetyError(f"room {channel_id!r} has unsupported effort {effort!r}")
    allowed_models = config.get("models")
    if not isinstance(allowed_models, list) or not allowed_models:
        raise SafetyError("model-config.json must define a non-empty models allowlist")
    if model not in allowed_models or not model.startswith("claude-"):
        raise SafetyError(f"room {channel_id!r} model {model!r} is not allowlisted")
    if role not in {"eng", "support"}:
        raise SafetyError(f"room {channel_id!r} has unsupported role {role!r}")

    return RoomPolicy(
        root=root,
        permission_mode=permission_mode,
        overlay=overlay.absolute(),
        escalation_channel=str(entry["private_escalation_channel"]),
        backend=backend,
        model=model,
        effort=effort,
        role=role,
    )


def _git(repo: Path, *args: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), *args],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise SafetyError(f"cannot inspect git checkout {repo}") from exc
    return result.stdout.strip()


def _check_shared_clone(repo: Path, name: str) -> list[str]:
    if not repo.is_dir():
        raise SafetyError(f"{name} clone is missing: {repo}")
    branch = _git(repo, "branch", "--show-current")
    if branch != "master":
        raise SafetyError(f"{name} clone is on {branch or 'detached HEAD'}, expected master")
    if _git(repo, "status", "--porcelain"):
        raise SafetyError(f"{name} clone is not clean")

    warnings = []
    try:
        behind = int(_git(repo, "rev-list", "--count", "HEAD..origin/master") or "0")
    except (SafetyError, ValueError):
        warnings.append(f"{name} local origin/master staleness could not be checked")
    else:
        if behind:
            warnings.append(f"{name} is {behind} commit(s) behind local origin/master")
    return warnings


def _check_generated_agents(root: Path, kit: Path, role: str) -> None:
    agents = root / "AGENTS.md"
    try:
        installed = agents.read_text(encoding="utf-8")
        base = (kit / "AGENTS.base.md").read_text(encoding="utf-8").rstrip("\n")
        role_text = (kit / "roles" / role / "ROLE.md").read_text(encoding="utf-8").rstrip("\n")
    except OSError as exc:
        raise SafetyError(f"cannot read generated instruction inputs: {exc}") from exc
    if GENERATED_MARKER not in installed:
        raise SafetyError("AGENTS.md is not a generated Cargo Chief instruction file")
    generated = installed.split(GENERATED_MARKER, 1)[0].rstrip("\n")
    expected = f"{base}\n\n{role_text}"
    if generated != expected:
        raise SafetyError(f"AGENTS.md is stale for the configured {role} role")

    claude = root / "CLAUDE.md"
    if not claude.is_symlink() or claude.resolve() != agents.resolve():
        raise SafetyError("CLAUDE.md must be a symlink to AGENTS.md")


def preflight_room(policy: RoomPolicy) -> list[str]:
    root = policy.root
    if not root.is_dir():
        raise SafetyError(f"Cargo Chief root is missing: {root}")
    kit = root / "agent-kit"
    docs = root / "docs"
    warnings = _check_shared_clone(kit, "agent-kit")
    warnings.extend(_check_shared_clone(docs, "docs"))

    overlay = policy.overlay
    try:
        overlay_relative = overlay.relative_to(kit)
    except ValueError as exc:
        raise SafetyError("autonomous overlay must live inside agent-kit") from exc
    if not overlay.is_file() or overlay.is_symlink() or not overlay.read_text(encoding="utf-8").strip():
        raise SafetyError(f"autonomous overlay must be a non-empty regular file: {overlay}")
    try:
        tracked = _git(kit, "ls-files", "--error-unmatch", str(overlay_relative))
    except SafetyError as exc:
        raise SafetyError("autonomous overlay is not tracked by agent-kit") from exc
    if not tracked:
        raise SafetyError("autonomous overlay is not tracked by agent-kit")

    _check_generated_agents(root, kit, policy.role)
    return warnings


def build_claude_command(
    policy: RoomPolicy,
    *,
    initial_prompt: str,
    model_prompt: str = "",
    session_id: str | None = None,
) -> list[str]:
    overlay = policy.overlay.read_text(encoding="utf-8").strip()
    appended = "\n\n".join(part for part in (overlay, model_prompt.strip()) if part)
    command = [
        "claude", "-p", initial_prompt,
        "--input-format", "stream-json",
        "--output-format", "stream-json",
        "--verbose",
        "--effort", policy.effort,
        "--model", policy.model,
        "--permission-mode", policy.permission_mode,
        "--append-system-prompt", appended,
    ]
    if session_id:
        command.extend(["--resume", session_id])
    return command
